#!/bin/sh

folder=$1
mkdir $folder && cd $folder
git init .
cp ../PromptTemplate.md prompt.md
git add prompt.md && git commit -m "Created."

echo
echo "*** Please now use: 'cd $folder' before continuing"
echo

